### ISSUE TITLE
Does not run. Maybe regex problem on my datetime strings

### ISSUE THREAD

**Issue by relima** [hiimivantang/whatsapp-analytics#1]
I am getting:

Traceback (most recent call last):
  File "regex_example.py", line 143, in <module>
    main()
  File "regex_example.py", line 138, in main
    df_messages, df_actions = parser.process(content)
  File "regex_example.py", line 72, in process
    messages[-1].message += parsed[2]
IndexError: list index out of range

But I guess my problem has to do with regex on the datetimes. What I have is quite different from the datetime on your example: On mine, I have the following: 1/2/2016, 16:33

**Comment by hiimivantang** [comment]
yup, i can't cover all the possible date formats alone.. :)

probably you can add

date_patterns = {
"long_datetime" : "(?P<datetime>\d{1,2}\s{1}\w{3}(\s{1}|\s{1}\d{4}\s{1})\d{2}:\d{2})",
"short_datetime" : "(?P<datetime>\d{2}/\d{2}/\d{4},\s{1}\d{2}:\d{2})",
"relima_datetime" : "(?P<datetime>\d{1,2}/\d{1,2}/\d{4},\s{1}\d{2}:\d{2})"
}

btw d{1,2} means either 1 or 2 digit

**Comment by hiimivantang** [comment]
will treat this issue as closed.
